<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>DiagnoseMeIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\Images\**" />
    <EmbeddedResource Remove="Resources\Images\**" />
    <None Remove="Resources\Images\**" />
    <Page Remove="Resources\Images\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\JSON\SymptomsQuestions_PL.json" />
    <None Remove="Resources\JSON\Symptoms_PL.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="DiagnoseMeIcon.ico" />
    <Content Include="Resources\JSON\Symptoms_PL.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\JSON\SymptomsQuestions_PL.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Controls\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Windows\LogInWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
